### ISSUE TITLE
Consolidated documentation tracker

### ISSUE THREAD

**Issue by alizma** [METHODS-Group/DRDMannTurb#45]
Rather than having 2 general issues about documentation, here is a tracker of which parts of the documentation are completed, in the same order as presented in the documentation. Marking a submodule as completed ensures both that the relevant math is included and that all parameters and class fields are documented. 

- [ ] Spectra Fitting
  - [ ] Data types and Dataclasses
  - [ ] Spectra Learning (calibration class) 
  - [ ] Spectra data generator/preprocessing 
  - [x] Loss Function set-up and evaluation
  - [x] Spectra interpolation
- [ ] Wind Generation
  - [ ] GenerateWind class
  - [x] Plotting utilities
  - [ ] GRFs
  - [ ] Covariance kernels (including NN)
  - [ ] Sampling Methods
- [ ] Internal API
  - [ ] NN architectures used for Eddylifetime 
  - [ ] Internal MLP and Ra nets
