### ISSUE TITLE
Consolidated documentation tracker

### ISSUE THREAD

**Issue by alizma** [METHODS-Group/DRDMannTurb#46]
Rather than having 2 general issues about documentation, here is a tracker of which parts of the documentation are completed, in the same order as presented in the documentation. Marking a submodule as completed ensures both that the relevant math is included and that all parameters and class fields are documented. 

**NOTE**: this issue will not be closed until approval that the documentation properly describes the package's functionality is given.

- [x] Spectra Fitting
  - [x] Data types and Dataclasses
  - [x] Spectra Learning (calibration class) 
  - [x] Spectra data generator/preprocessing 
  - [x] One Point Spectra and Eddy Lifetime learning set-up
  - [x] Power Spectra
  - [x] Loss Function set-up and evaluation
  - [x] Spectra interpolation
- [x] Wind Generation
  - [x] GenerateFluctuationField class
  - [x] Plotting utilities
- [x] Internal API
  - [x] NN architectures used for Eddylifetime 
  - [x] Internal MLP and Ra nets
  - [x] Covariance kernels (including NN)
  - [x] Sampling Methods
  - [x] GRFs
